name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  buildImage:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Container image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log in to GitHub Container Registry
        run: echo "${{ secret.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/Top-api:${{ github.run_id }}
          docker push $IMAGE_ID